// auto generated by bootstrap
#ifndef _Oatom_H_
#define _Oatom_H_

enum
{
    SETTINGS_GROUP = 95044138,
    SETTINGS_STRENGTH = 27890828,
    GROUP_LABEL_OFFSET = 69677796,
    SETTINGS_OFFSET = 15150201,
};

#endif
