// auto generated by bootstrap
CONTAINER Ttest
{
    NAME Ttest;
    INCLUDE Tbase;
    INCLUDE Texpression;

    GROUP SETTINGS_GROUP
    {
        DEFAULT 1;
    
        REAL SETTINGS_STRENGTH
        {
            MIN 0.0;
            MAX 100.0;
        
            
        }
        
        GROUP GROUP_LABEL_OFFSET
        {
            INCLUDE Tbase;
            INCLUDE Texpression;
        
            VECTOR SETTINGS_OFFSET
            {
                
            
                
            }
            
        }
        
    }
    
}
